CREATE TABLE IF NOT EXISTS crimes (
  id BIGINT NOT NULL,
  case_number VARCHAR(50) NULL,
  date DATETIME NULL,
  block VARCHAR(100) NULL,
  iucr VARCHAR(10) NULL,
  primary_type VARCHAR(100) NULL,
  description VARCHAR(255) NULL,
  location_description VARCHAR(255) NULL,
  arrest TINYINT(1) NULL,
  domestic TINYINT(1) NULL,
  beat VARCHAR(10) NULL,
  district VARCHAR(10) NULL,
  ward INT NULL,
  community_area INT NULL,
  fbi_code VARCHAR(10) NULL,
  x_coordinate DOUBLE NULL,
  y_coordinate DOUBLE NULL,
  year INT NULL,
  updated_on DATETIME NULL,
  latitude DOUBLE NULL,
  longitude DOUBLE NULL,
  location VARCHAR(255) NULL,
  PRIMARY KEY (id),
  KEY idx_crimes_year (year),
  KEY idx_crimes_date (date),
  KEY idx_crimes_primary_type (primary_type),
  KEY idx_crimes_district (district),
  KEY idx_crimes_arrest (arrest),
  KEY idx_crimes_domestic (domestic)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

